name: Pipeline

on: [push, workflow_dispatch]

env:
  SERVICE_NAME: mascot-api

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install requirements
        run: pip install --requirement development-requirements.txt

      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 *.py

      - name: Run unit tests
        run: python -m unittest --verbose --failfast
